let fruits=["apple","banana","orange","grape","mango"];
console.log(fruits[0]);
console.log(fruits[2]);
console.log(fruits[4]);

console.log("------------------");
console.log("an array with mixed datatypes.");
let mixedArray=[1, "hello", true, null, undefined];
console.log(mixedArray);
console.log(mixedArray[0]);
console.log(mixedArray[1]);

console.log("-------------------");
console.log("find the length of an array.");
let numbers=[10,20,30,40,50];
console.log(numbers);
console.log(numbers.length);

console.log("------------------");
console.log("add an element to the end of an array.");
let colors=["red","green","blue"];
console.log(colors);
colors.push("yellow");
console.log(colors);
console.log("---------------------");
console.log("remove the last element from an array.");
colors.pop();
console.log(colors);
console.log("---------------------");
console.log("add an element to the beginning of an array.");
colors.unshift("purple");
console.log(colors);
console.log("---------------------");
console.log("remove the first element from an array.");
colors.shift();
console.log(colors);
console.log("---------------------");
console.log("find the index of an element in an array.");
let index=colors.indexOf("green");
console.log("Index of green:",index);
console.log("---------------------");
console.log("check if an element exists in an array.");
let exists=colors.includes("blue");
console.log("Does blue exist?",exists);
console.log("---------------------");
console.log("slice an array to get a portion of it.");
let numbers2=[1,2,3,4,5,6,7,8,9];
let slicedNumbers=numbers2.slice(2,5);
console.log("Sliced numbers:", slicedNumbers);
console.log("---------------------");
console.log("concatenate two arrays.");
let array1=[1,2,3];
let array2=[4,5,6];
let concatenatedArray=array1.concat(array2);
console.log("Concatenated array:",concatenatedArray);
console.log("---------------------");
console.log("sort an array in ascending order.");
let unsortedArray=[5,2,9,1,5,6];
console.log("Unsorted array:",unsortedArray);
unsortedArray.sort((a,b)=>a-b);
console.log("Sorted array:",unsortedArray);
console.log("---------------------");
console.log("reverse the order of an array.");
let reversedArray=[1,2,3,4,5];
console.log("Original array:",reversedArray);
reversedArray.reverse();
console.log("Reversed array:",reversedArray);
console.log("---------------------");
console.log("join elements of an array into a string:");
let words=["Hello","World","JavaScript"];
console.log("Words array:",words);
let joinedString=words.join(" ");
console.log("Joined string:",joinedString);
console.log("---------------------");
console.log("split a string into an array:");
let sentence="Hello World JavaScript";
console.log("Original sentence:",sentence);
let splitArray=sentence.split(" ");
console.log("Split array:",splitArray);
console.log("---------------------");
console.log("find the maximum value in an array:");
let values=[10,5,8,20,15];
console.log("Values array:",values);
let maxValue=Math.max(...values); //... used to copy the elements of the array as individual arguments to Math.max from the old values array
console.log("Maximum value:",maxValue);
console.log("---------------------");
console.log("find the minimum value in an array:");
let minValue=Math.min(...values);
console.log("Minimum value:",minValue);
console.log("---------------------");
console.log("filter an array based on a condition:");
let filteredValues=values.filter(value=>value>10);
console.log("Filtered values (greater than 10):",filteredValues);
console.log("---------------------");
console.log("map an array to create a new array:"); //array.map((element) => {   });
let squaredValues=values.map(value=>value*value);
console.log("Squared values:",squaredValues);
console.log("---------------------");
console.log("reduce an array to a single value:");
let sum=values.reduce((a,b)=>a+b,0);
console.log("Sum of values:",sum);
console.log("---------------------");
console.log("find the average of an array:");
let average=sum/values.length;
console.log("Average value:",average);
console.log("---------------------");
console.log("check if all elements in an array satisfy a condition:");
let allGreaterThan5=values.every(value=>value>5);
console.log("Are all values greater than 5?",allGreaterThan5);
console.log("---------------------");
console.log("check if any element in an array satisfies a condition:");
let anyGreaterThan15=values.some(value=>value>15);
console.log("Is any value greater than 15?",anyGreaterThan15);
console.log("---------------------");
console.log("find the index of the first element that satisfies a condition:");
let firstGreaterThan10Index=values.findIndex(value=>value>10);
console.log("Index of first value greater than 10:",firstGreaterThan10Index);
console.log("---------------------");
console.log("find the first element that satisfies a condition:");
let firstGreaterThan10=values.find(value=>value>10);
console.log("First value greater than 10:",firstGreaterThan10);
console.log("---------------------");
